#!/bin/bash
# OpenXX MCP Auth Setup Script
# Generates a random token and sets it for both MCP server and WhatsApp bot.

set -e

ENV_FILE=".env"
ENV_EXAMPLE=".env.example"

echo "=== OpenXX MCP Auth Setup ==="
echo ""

# Generate random token
TOKEN=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 64)

if [ -z "$TOKEN" ]; then
    echo "ERROR: Failed to generate token. Install openssl or ensure /dev/urandom exists."
    exit 1
fi

echo "Generated token: ${TOKEN:0:8}...${TOKEN: -8}"
echo ""

# Create .env if not exists
if [ ! -f "$ENV_FILE" ]; then
    if [ -f "$ENV_EXAMPLE" ]; then
        cp "$ENV_EXAMPLE" "$ENV_FILE"
        echo "Created .env from .env.example"
    else
        touch "$ENV_FILE"
        echo "Created empty .env"
    fi
fi

# Update or add OPENX_MCP_API_KEY in .env
if grep -q "^OPENX_MCP_API_KEY=" "$ENV_FILE" 2>/dev/null; then
    sed -i.bak "s/^OPENX_MCP_API_KEY=.*/OPENX_MCP_API_KEY=$TOKEN/" "$ENV_FILE"
    rm -f "$ENV_FILE.bak"
    echo "Updated OPENX_MCP_API_KEY in .env"
else
    echo "" >> "$ENV_FILE"
    echo "# MCP Auth Token (generated by setup-mcp-auth.sh)" >> "$ENV_FILE"
    echo "OPENX_MCP_API_KEY=$TOKEN" >> "$ENV_FILE"
    echo "Added OPENX_MCP_API_KEY to .env"
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Token saved to .env as OPENX_MCP_API_KEY"
echo ""
echo "For MCP Server (Termux/Railway), set this env var:"
echo "  export OPENX_HTTP_API_KEY=$TOKEN"
echo ""
echo "Or add to your MCP server's .env:"
echo "  OPENX_HTTP_API_KEY=$TOKEN"
echo ""
echo "IMPORTANT: Both values must match for auth to work."
