import { Command } from 'commander';
import prompts from 'prompts';
import fs from 'fs';
import path from 'path';

export const initCommand = new Command('init')
  .description('Interactive setup wizard')
  .action(async () => {
    console.log('\n=== OpenXX Setup Wizard ===\n');

    const response = await prompts([
      {
        type: 'text',
        name: 'baseUrl',
        message: 'AI base URL (OpenAI-compatible)?',
        initial: 'https://ai.sumopod.com'
      },
      {
        type: 'password',
        name: 'apiKey',
        message: 'AI API key?'
      },
      {
        type: 'text',
        name: 'model',
        message: 'Default model?',
        initial: 'gpt-4o-mini'
      }
    ]);

    if (response.cancelled) {
      console.log('Setup cancelled.');
      return;
    }

    const envLines = [
      '# OpenXX Configuration (generated by openxx-setup)',
      '',
      '# AI API (OpenAI-compatible)',
      `OPENX_OPENAI_BASE_URL=${response.baseUrl}`,
      `OPENX_OPENAI_API_KEY=${response.apiKey || ''}`,
      `OPENX_OPENAI_MODEL=${response.model}`,
      '',
      '# FGSi API (for .search and .img)',
      'OPENX_FGSI_BASE_URL=https://fgsi.dpdns.org/api/ai/claude',
      'OPENX_FGSI_API_KEY='
    ];

    fs.writeFileSync(path.resolve(process.cwd(), '.env'), envLines.join('\n') + '\n');
    console.log('\n✅ Created .env');
    console.log('\n=== Next Steps ===');
    console.log('1. Edit .env and fill in missing values');
    console.log('2. Start bot: pnpm start');
  });
