import { Command } from 'commander';
import prompts from 'prompts';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

export const initCommand = new Command('init')
  .description('Interactive setup wizard')
  .action(async () => {
    console.log('\n=== OpenXX Setup Wizard ===\n');

    const response = await prompts([
      {
        type: 'select',
        name: 'mode',
        message: 'Deployment mode?',
        choices: [
          { title: 'VPS only (WhatsApp bot on server)', value: 'vps' },
          { title: 'VPS + Android (bot on VPS, MCP on phone)', value: 'both' },
          { title: 'Local (everything on this machine)', value: 'local' }
        ]
      },
      {
        type: 'select',
        name: 'aiProvider',
        message: 'AI Provider?',
        choices: [
          { title: 'OpenAI-compatible (SumoPod, Together, etc.)', value: 'openai' },
          { title: 'OpenRouter (multi-model)', value: 'openrouter' },
          { title: 'Custom REST API', value: 'rest' }
        ]
      },
      {
        type: 'select',
        name: 'adbMode',
        message: 'ADB mode?',
        choices: [
          { title: 'USB (phone connected via cable)', value: 'usb' },
          { title: 'Auto-detect TCP port', value: 'auto' },
          { title: 'Not needed', value: 'none' }
        ]
      },
      {
        type: 'confirm',
        name: 'generateToken',
        message: 'Generate MCP auth token?',
        initial: true
      }
    ]);

    if (response.cancelled) {
      console.log('Setup cancelled.');
      return;
    }

    const token = response.generateToken ? crypto.randomBytes(32).toString('hex') : '';

    const envLines = [];
    envLines.push('# OpenXX Configuration (generated by openxx-setup)');
    envLines.push('');
    envLines.push('# WhatsApp admin phone number');
    envLines.push('OPENX_DEV_PHONE_NUMBER=');
    envLines.push('');
    envLines.push('# AI Provider');
    envLines.push(`OPENX_AI_PROVIDER=${response.aiProvider}`);
    envLines.push('');

    if (response.aiProvider === 'openai') {
      envLines.push('# OpenAI-compatible API');
      envLines.push('OPENX_OPENAI_BASE_URL=https://ai.sumopod.com');
      envLines.push('OPENX_OPENAI_API_KEY=');
      envLines.push('OPENX_OPENAI_MODEL=gpt-4o-mini');
    } else if (response.aiProvider === 'openrouter') {
      envLines.push('# OpenRouter');
      envLines.push('OPENX_OPENROUTER_API_KEYS=');
    } else {
      envLines.push('# Custom REST API');
      envLines.push('OPENX_REST_BASE_URL=');
      envLines.push('OPENX_REST_API_KEY=');
      envLines.push('OPENX_REST_MODEL=');
    }

    envLines.push('');
    envLines.push('# ADB');
    envLines.push(`OPENX_ADB_PORT=${response.adbMode}`);
    envLines.push('');
    envLines.push('# MCP Server');
    envLines.push('OPENX_MCP_URL=http://localhost:8765');
    envLines.push(`OPENX_MCP_API_KEY=${token}`);

    if (response.mode === 'both') {
      envLines.push('');
      envLines.push('# Tunnel (for VPS + Android mode)');
      envLines.push('# Set after running: openxx-setup tunnel');
    }

    const envPath = path.resolve(process.cwd(), '.env');
    fs.writeFileSync(envPath, envLines.join('\n') + '\n');
    console.log(`\n✅ Created .env`);

    if (token) {
      console.log(`\n📋 MCP Auth Token: ${token}`);
      console.log('   Save this — you\'ll need it for the MCP server side.');
    }

    console.log('\n=== Next Steps ===');
    console.log('1. Edit .env and fill in your values');
    if (response.mode === 'both') {
      console.log('2. On Android: install Termux, build MCP server');
      console.log('3. Run: openxx-setup tunnel');
      console.log('4. Start bot: pnpm start');
    } else {
      console.log('2. Start bot: pnpm start');
    }
  });
